# Generated by Django 3.0.5 on 2020-04-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=200)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('address', models.CharField(max_length=200)),
                ('image_make', models.CharField(max_length=10)),
                ('image_model', models.CharField(max_length=10)),
            ],
        ),
    ]
