# Generated by Django 3.0.5 on 2020-04-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200419_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_make',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_model',
            field=models.CharField(max_length=50),
        ),
    ]
